ruby_notes/config/routes.rb
Rails.application.routes.draw do
  get 'invoices/index'
  get 'invoices/show'
  root to: "home#index"
  get 'home/index'
  devise_for :users

  resources :books
  put 'books/:id', controller: 'books', action: :update


  resources :notes
  get 'download_note',controller: 'notes', action: :download
  get 'downloadnotes_book',controller: 'books', action: :download_notes

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users do
    get 'download'
    # file: rails-generate-pdf/app/config/routes.rb
  root to: 'invoices#index'
  resources :invoices, only: [:index, :show]
  end
end

ruby_notes/app/models/note.rb
class Note < ApplicationRecord
  belongs_to :book

  validates :title, presence: true, length: {maximum:255}
  validates :content, presence:true

  def to_s
    title
  end

end

ruby_notes/app/controllers/notes_controller.rb
class NotesController < ApplicationController
  def index
    redirect_to '/'
  end

  def show
    @books = current_user.books
    ok = false
    for book in @books
      if book.containNote(params[:id])
        @note = Note.where(id: params[:id]).first()
        ok = true
        break
      end
    end
    if !ok
      flash.alert = "The note does not exist"
      redirect_to '/'
    end
  end

  def create
    if params[:title].blank?
      flash.alert = "The title can't be blank"
      redirect_back(fallback_location: root_path)
    elsif params[:content].blank?
      flash.alert = "The content can't be empty"
      redirect_back(fallback_location: root_path)
    else
    current_user.books.find(params[:book_id]).notes.create(title: params[:title],content:params[:content], book_id: params[:book_id])
    redirect_to ( '/books/'+params[:book_id])
  end
  end

  def edit

    @books = current_user.books
    ok = false
    for book in @books
      if book.containNote(params[:id])
        @note = Note.where(id: params[:id]).first()
        ok = true
        break
      end
    end
    ##MODULARIZAR
    if @note
       @note
    else
      redirect_to '/'
    end
  end

  def update
    if params[:note][:title].blank?
      flash.alert = "The title can't be blank"
      redirect_back(fallback_location: root_path)
    elsif params[:note][:content].blank?
      flash.alert = "The content can't be empty"
      redirect_back(fallback_location: root_path)
    else
    @books = current_user.books
    ok = false
    for book in @books
      if book.containNote(params[:id])
        @note = Note.where(id: params[:id]).first()
        ok = true
        break
      end
    end
    if @note
      @note.update(title: params[:note][:title],content:params[:note][:content], book_id: params[:note][:book_id])
    end
    redirect_to ( '/books/'+params[:note][:book_id])
  end
  end

  def destroy
    @books = current_user.books
    ok = false
    for book in @books
      if book.containNote(params[:id])
        @note = Note.where(id: params[:id]).first()
        ok = true
        break
      end
    end
    if @note
      @note.destroy
    else
      redirect_to '/'
    end
    redirect_to '/books'
  end

  def download
       @note = Note.find(params[:note_id])
       html = render_to_string(:action => :download, :layout => false)
       pdf = WickedPdf.new.pdf_from_string(html)
       send_data(pdf,
           :filename    => "temp.pdf",
           :disposition => 'attachment')
    end
end

ruby_notes/app/views/notes/download.html.erb
<%= wicked_pdf_stylesheet_link_tag 'downloader' %>
<div class="some-div">
  <div class="some-other-div">

    Title Note:<br>
    <div>
      <%= @note.title, class: "card title"%><br>

    </div>


      Content:<br>

      <textarea name="name" rows="400" cols="150"><%= @note.content %></textarea>
        <br>

      View in markdown:<%= markdown(@note.content) %><br>

  </div>
</div>

ruby_notes/app/views/notes/edit.html.erb
<h1><%= link_to "#{@note.book.title}", @note.book %>
  ->
<%= link_to "#{@note}", @note.book %>
  -> Edit</h1>
<%= form_for(@note) do |form| %>
<div>
    <%= form.label :title, "Title:",{class:"card-title"} %><br>
    <%= form.text_field :title,  :maxlength => 255, :size => 100  %><br>
</div>
<div>
  <%= form.label :content, "Content:" %><br>
  <%= form.text_area :content,{maxlength:"65535",class:"md-textarea form-control",rows:16} %>
</div>

<div>
  <%= form.select :book_id, current_user.books.collect { |b| [b.title,b.id] } %>
</div>
  <%= form.submit "Save" %>
<% end %>

ruby_notes/app/views/notes/new.html.erb
<h1>New Note</h1>

<div class="card w-75">
  <div class="card-body">
<%= form_with url: "/notes", method: :post do |form| %>
<div >
    <%= form.label :title, "Title:",{class:"card-title"} %><br>
    <%= form.text_field :title, :maxlength => 255, :size => 100 %><br>
</div>
<br>
<div>
  <%= form.select :book_id, current_user.books.collect { |b| [b.title,b.id] } %>
</div>
<br>
<div>
  <%= form.label :content, "Content:" %><br>
  <%= form.text_area :content,{maxlength:"65535",class:"md-textarea form-control",rows:16} %>
</div>

  <%= form.submit "Save" ,{class:"btn btn-primary"} %>
  <% end %>

  </div>
</div>

ruby_notes/app/views/notes/show.html.erb
<div class="some-div">
  <div class="some-other-div">
    <div class="card title">
    <h3>  Title Note:<br></h3>
    </div>

    <div class="container">
      <h4><%= @note.title %><br></h4>
    </div>
    <hr>

    <div class="card title">
    <h3>  Content:<br></h3>
    </div>

    <div class="container">

      <textarea name="name" rows="400" cols="120">

        <%= @note.content %></textarea>
    </div>

        <br>
    <hr>
    <h3>View in markdown:</h3>

    <div class="container">
      <%= markdown(@note.content) %><br>
    </div>
  </div>
</div>


  <h1> <%= link_to "#{@note.book.title}", @note.book %> -> <%= @note.title %> </h1>
<hr>
<%= form_for(@note) do |form| %>
<div>
    <%= form.label :title, "Title:",{class:"card-title"} %><br>
    <%= form.text_field :title, :readonly => true %><br>
</div>
<br>
<div>
  <%= form.label :content, "Content:" %><br>
  <%= form.text_area :content,{id:"InputTextArea", class:"md-textarea form-control",rows:16, readonly:true} %>
</div>
<% end %>

<div>
<hr>
<%= link_to "Edit", edit_note_path(@note), class: "btn btn-primary"%>
<%= link_to "PDF", download_note_path(:note_id => @note.id), class: "btn btn-success" %>
<%= link_to "Destroy", @note, method: :delete, data: { confirm: "Are you sure?" },class: "btn btn-danger" %>
</div>
<hr>
<div>
<h3>View in Markdown</h3>
<hr>
</div>
<%= markdown(@note.content) %>

<script >
  function resizeTextarea (id) {
  var a = document.getElementById(id);
  a.style.height = 'auto';
  a.style.height = a.scrollHeight+'px';
}

function init() {
  var a = document.getElementsByTagName('textarea');
  for(var i=0,inb=a.length;i<inb;i++) {
     if(a[i].getAttribute('data-resizable')=='true')
      resizeTextarea(a[i].id);
  }
}

addEventListener('DOMContentLoaded', init);
  </script>