ruby_notes/config/routes.rb
Rails.application.routes.draw do
  get 'invoices/index'
  get 'invoices/show'
  root to: "home#index"
  get 'home/index'
  devise_for :users

  resources :books
  put 'books/:id', controller: 'books', action: :update


  resources :notes
  get 'download_note',controller: 'notes', action: :download
  get 'downloadnotes_book',controller: 'books', action: :download_notes

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users do
    get 'download'
    # file: rails-generate-pdf/app/config/routes.rb
  root to: 'invoices#index'
  resources :invoices, only: [:index, :show]
  end
end

ruby_notes/app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user

  has_many :notes, inverse_of: :book, dependent: :delete_all

  validates_uniqueness_of :title, presence:true, scope: :user_id, length: {maximum:255 }
  validates :title, presence: {message: "Cant be blank"}, length: {maximum:255}

  def to_s
    title
  end

  def containNote(id)
    ok = false
    if self.notes.exists? (id)
      return true
    end
    ok
  end

  def exportAll
    for note in self.notes
      note.export
    end
  end

end

ruby_notes/app/controllers/books_controller.rb
class BooksController < ApplicationController
  require 'zip'
  def index
    @books = current_user.books
  end

  #display the books of the authenticated user

  def show
    if current_user.books.exists?(params[:id])
      @book = current_user.books.find(params[:id])
      @notes = @book.notes
    else
      render(:file =>File.join(Rails.root,'public/403.html'), :status => 403, :layout => false)
    end
  end

  #create a new book for the authenticated user
  def create
    if params[:title].blank?
      flash.alert = "The title can't be blank"
      redirect_back(fallback_location: root_path)
    elsif current_user.books.exists?(title: params[:title])
      flash.alert = "The name is alredy in use"
      redirect_back(fallback_location: root_path)
    else
      current_user.books.create(title: params[:title], user_id: current_user.id)
      redirect_to '/books'
    end
  end

  #edit a book for the authenticated user
  def edit
    if current_user.books.exists?(params[:id])
      @book = current_user.books.find(params[:id])
      if @book.title == "Global"
        redirect_to '/'
      end
    else
      render(:file =>File.join(Rails.root,'public/403.html'), :status => 403, :layout => false)
    end
  end

  def update
    if params[:book][:title].blank?
      flash.alert = "The title can't be blank"
      redirect_back(fallback_location: root_path)
    elsif current_user.books.exists?(title: params[:book][:title])
      flash.alert = "The name is alredy in use"
      redirect_back(fallback_location: root_path)
    else

    @books = current_user.books
    if @books.exists?(params[:id])
      @book = current_user.books.find(params[:id])
      if @book.title == "Global"
        flash.alert = "Cant update Global book"
        redirect_to '/'
      end
      @book.update(title: params[:book][:title])
      redirect_to '/books/'
    else
      render(:file =>File.join(Rails.root,'public/403.html'), :status => 403, :layout => false)

    end
    end
  end

  #delete a book and the content for the authenticated user
  def destroy
    if current_user.books.exists?(params[:id])
      @book = current_user.books.find(params[:id])
      if @book.title != "Global"
        @book.destroy
      end
    else
      render(:file =>File.join(Rails.root,'public/403.html'), :status => 403, :layout => false)
    end
    redirect_to '/books'

  end

  def download_notes
    @notes = current_user.books.find(params[:book_id]).notes
    stringio = Zip::OutputStream.write_buffer do |zio|
      @notes.each do |coverage|
        #create and add a text file for this record
        zio.put_next_entry("#{coverage.id}_test.txt")
        zio.write "#{coverage.title}!"
        #create and add a pdf file for this record
        dec_pdf = render_to_string :pdf => "#{coverage.id}_dec.pdf", :template => 'books/download', :locals => {coverage: coverage}
        zio.put_next_entry("#{coverage.id}_dec.pdf")
        zio << dec_pdf
      end
    end
    # This is needed because we are at the end of the stream and
    # will send zero bytes otherwise
    stringio.rewind
    #just using variable assignment for clarity here
    binary_data = stringio.sysread
    send_data(binary_data, :type => 'application/zip', :filename => "test_dec_page.zip")
  end

end

ruby_notes/app/views/books/download.html.erb
<%= wicked_pdf_stylesheet_link_tag 'downloader' %>
<div class="some-div">
   <%= @notes.each do |note| %>
  <div class="some-other-div">
    <p>

       Title Note:<br>
       <%= note.title %><br>

      Content:<br>

      <textarea name="name" rows="400" cols="150"><%= note.content %></textarea>
        <br>

      View in markdown:<%= markdown(note.content) %><br>
    </p>
  </div>
  <% end %>
</div>

ruby_notes/app/views/books/edit.html.erb
<h1>Edit Book</h1>

  <h3>
   <%= link_to "#{@book.title}", @book %>
  </h3>
<br>
<%= form_for(@book) do |form| %>
  <%= form.label :title, "Title:" %>
  <%= form.text_field :title, :maxlength => 255, :size => 100 %><br><br>
  <%= form.submit "Save" ,class:"btn btn-primary" %>
<% end %>

ruby_notes/app/views/books/index.html.erb
<div>
  <h1>Your Books</h1>

  <h3>
  <%= link_to "New book", new_book_path %>
  </h3>
</div>
<table class="table">
  <thead>
    <tr>
      <th scope="col">Title</th>
      <th scope="col"></th>
      <th scope="col"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= link_to "#{book.title}", book %></td>
        <% if not book.title == "Global" %>
        <td><%= link_to "Edit", edit_book_path(book) ,class: "btn btn-primary"%></td>

        <td><%= link_to "Destroy", book, method: :delete, data: { confirm: "Are you sure? All notes will be deleted" },class: "btn btn-danger" %></td>
        <% end %>

      </tr>
    <% end %>
  </tbody>
</table>

<br>

ruby_notes/app/views/books/new.html.erb
<h1>New Book</h1>
<div class="card w-75">
  <div class="card-body">

<%= form_with url: "/books", method: :post do |form| %>
<div>
    <%= form.label :title, "Title:",{class:"card-title"} %><br>
    <%= form.text_field :title, :maxlength => 255, :size => 100 %><br>
</div>
<br>
<%= form.submit "Save" ,class:"btn btn-primary"%>
<% end %>
</div>
</div>

ruby_notes/app/views/books/show.html.erb
<div>
<h1> <%= @book.title %> </h1>
 <h3>  <%= link_to "New Note", new_note_path %> </h3>
</div>



<%= link_to 'Export all PDFS', downloadnotes_book_path(:book_id => @book.id) %>

<table class="table">
  <thead>
    <tr>
      <th scope="col">Title</th>
      <th scope="col"></th>
      <th scope="col"></th>
    </tr>
  </thead>

  <tbody>
    <% @notes.each do |note| %>
      <tr>
        <td><%= link_to "#{note.title}", note %></td>
        <td><%= link_to "Edit", edit_note_path(note),class: "btn btn-primary" %></td>
        <td><%= link_to "Destroy", note,
          method: :delete,class: "btn btn-danger",
          data: { confirm: "Are you sure?" } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>